sonar.projectKey=tasuketejs
sonar.projectName=TasuketeJS
sonar.projectVersion=0.1.0

sonar.sources=packages/core/src
sonar.tests=packages/core/test
sonar.test.inclusions=**/*.test.ts
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=packages/core/coverage/lcov.info

sonar.exclusions=**/dist/**,**/coverage/**,**/node_modules/**,**/*.d.ts
sonar.coverage.exclusions=packages/core/src/index.ts
